version: '3'
services:
  pgserver1:
    image: postgres:latest
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=watermelon
    volumes: 
      - ./pgdata1:/var/lib/postgres/data
    networks: 
      - go_bridge
  pgserver2:
    image: postgres:latest
    ports: 
      - 5433:5432
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=watermelon
    volumes: 
      - ./pgdata2:/var/lib/postgres/data
    networks: 
      - go_bridge
  command:
    build: article_api/command/.
    environment: 
      - DATABASE_URL=postgres://postgres:postgres@pgserver1:5432/
      - DATABASE_NAME=watermelon
      - API_ENV=http://nginx:8080
    networks: 
      - go_bridge
    depends_on:
      - pgserver1
      - query
    restart: on-failure
  query:
    build: article_api/query/.
    environment: 
      - DATABASE_URL=postgres://postgres:postgres@pgserver2:5432/
      - DATABASE_NAME=watermelon
    networks: 
      - go_bridge
    depends_on:
      - pgserver2
    restart: on-failure
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks: 
      - go_bridge
    depends_on:
      - pgserver1
      - query
      - command
    restart: on-failure

networks:
  go_bridge:
    driver: bridge
